### ISSUE TITLE
Error http 423 (Locked)

### ISSUE THREAD

**Issue by rdehuyss** [kvj/hass_nuki_ng#103]
Hi,

Thanks for this great integration - awesome work! 

I'm using this with the Nuki Smart Lock 3.0 Pro and sometimes receive the following error:
`Http response for https://api.nuki.io/smartlock/{my lock id}/action: 423 Locked.`

I do think this is more related to Nuki but I was wondering if anybody else is having this issue? This is becoming an issue as it also happens when we leave, the automation runs but the door doesn't get locked.

Thanks!

**Comment by MacVille** [comment]
I have the same issue. 
with this extend Log entry
`websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Http response for https://api.nuki.io/smartlock/ID/action: 423 Locked
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/nuki_ng/lock.py", line 53, in async_lock
    await self.coordinator.action(self.device_id, "lock")
  File "/config/custom_components/nuki_ng/nuki.py", line 469, in action
    await self.api.web_lock_action(self.web_id(dev_id), action)
  File "/config/custom_components/nuki_ng/nuki.py", line 126, in web_lock_action
    await self.web_async_json(
  File "/config/custom_components/nuki_ng/nuki.py", line 184, in web_async_json
    return await self.async_json(
  File "/config/custom_components/nuki_ng/nuki.py", line 39, in async_json
    raise ConnectionError(f"Http response for {response.request.url}: {response.status_code} {response.reason}")
ConnectionError: Http response for https://api.nuki.io/smartlock/ID/action: 423 Locked`
