### ISSUE TITLE
Timestamp error

### ISSUE THREAD

**Issue by alexdelprete** [kvj/hass_nuki_ng#106]
It happens quite often...date/time format issue?

![image](https://user-images.githubusercontent.com/7027842/190453639-a9e1269c-7748-4467-b41e-99cba414d2af.png)

**Comment by craibo** [comment]
I am also seeing this issue constantly. 
73 occurrences in under 12 hours at night when the lock was not even being used.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 381, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/nuki_ng/sensor.py", line 220, in extra_state_attributes
    "timestamp": datetime.fromisoformat(timestamp) if not None else None,
TypeError: fromisoformat: argument must be str`
