### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by luigicasa** [kvj/hass_nuki_ng#134]
![immagine](https://user-images.githubusercontent.com/122391198/213513396-7d962ac9-367b-43ee-8f31-37ae3a873f1e.png)

![immagine](https://user-images.githubusercontent.com/122391198/213513512-192cee5a-dd9b-48b3-930d-c7db82c9b702.png)

![immagine](https://user-images.githubusercontent.com/122391198/213513559-93d8e22a-bc5a-4274-aaeb-7d33eda86e2d.png)

![immagine](https://user-images.githubusercontent.com/122391198/213513598-2b3e156d-3d05-45ce-b0a0-b7429502010a.png)

Logger: custom_components.nuki_ng.config_flow
Source: helpers/network.py:201
Integration: Nuki Lock ([documentation](https://github.com/kvj/hass_nuki_ng), [issues](https://github.com/kvj/hass_nuki_ng/issues))
First occurred: 17:59:32 (1 occurrences)
Last logged: 17:59:32
Error getting HASS url:

Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/config_flow.py", line 61, in _get_hass_url
    return get_url(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

Logger: homeassistant.config_entries
Source: helpers/network.py:201
First occurred: 17:59:55 (1 occurrences)
Last logged: 17:59:55
Error setting up entry Porta di casa for nuki_ng

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nuki_ng/__init__.py", line 25, in async_setup_entry
    coordinator = NukiCoordinator(hass, entry, data)
  File "/config/custom_components/nuki_ng/nuki.py", line 344, in __init__
    url = config.get("hass_url", get_url(hass))
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by alexdelprete** [comment]
Luigi, can you show the HA config.yaml please?

Also, please enclose all code/logs/etc. in comments (see the <> symbol in the top bar of the editor when writing/editing.

**Comment by alexdelprete** [comment]
This is the configuration you tried to input, right?

![image](https://user-images.githubusercontent.com/7027842/213515503-7b5d9d7f-3666-4da7-b0bd-3f6a2b421e5a.png)

**Comment by rmnbw73** [comment]
I have the same problem after a home assistant update, the integration no longer works.

**Comment by scaraps** [comment]
Same error! Any solution?

**Comment by orenshp** [comment]
Same here. 
Nuki 4 pro, no bridge needed, trying to use the Web API.
I'm putting only the Web Api token field and get the "NoURLAvailableError" in the logs.
