### ISSUE TITLE
Initiale configuration issue

### ISSUE THREAD

**Issue by ppernet** [kvj/hass_nuki_ng#141]
Hello,

I try to configure Nuki Lock pro 3 (without bridge) but I've errors at the end of process :
<img width="302" alt="Capture d’écran 2023-02-16 à 13 45 50" src="https://user-images.githubusercontent.com/89965535/219368679-48848e45-89f4-49c3-97b6-e246a4cbb4bd.png">

Logs says 2 errors:

---------------------
Logger: homeassistant.config_entries
Source: helpers/network.py:200 
First occurred: 12:03:58 (2 occurrences) 
Last logged: 13:42:04

Error setting up entry Serrure entrée for nuki_ng
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nuki_ng/__init__.py", line 25, in async_setup_entry
    coordinator = NukiCoordinator(hass, entry, data)
  File "/config/custom_components/nuki_ng/nuki.py", line 344, in __init__
    url = config.get("hass_url", get_url(hass))
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

------------------------

Logger: custom_components.nuki_ng.config_flow
Source: helpers/network.py:200 
Integration: Nuki Lock (documentation, issues) 
First occurred: 12:03:41 (2 occurrences) 
Last logged: 13:40:48

Error getting HASS url:
Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/config_flow.py", line 61, in _get_hass_url
    return get_url(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

--------------------------

I use external access with Duckdns.org and on LAN, I access to Home Assistant with https://------.duckdns.org too. I try to put this address in integration config but it don't work.

Any idea ?

Thank you.

**Comment by ppernet** [comment]
Sorry, I found solution : put https address in Config/network/local network and restart HA 👍


<img width="665" alt="Capture d’écran 2023-02-16 à 16 51 59" src="https://user-images.githubusercontent.com/89965535/219418045-0851d861-5733-4d4d-975a-1a3428765b8d.png">
