### ISSUE TITLE
NUKI LOCK DOESN'T WORK

### ISSUE THREAD

**Issue by Alex73hub** [kvj/hass_nuki_ng#147]
<img width="411" alt="Screenshot 2023-03-25 alle 22 11 08" src="https://user-images.githubusercontent.com/83889924/227742279-1b0957fc-db55-47ba-a12f-88fc1ea0e472.png"> <img width="339" alt="Screenshot 2023-03-25 alle 22  <img width="291" alt="Screenshot 2023-03-25 alle 22 13 00" src="https://user-images.githubusercontent.com/83889924/227742301-0cf7a9eb-9f0c-4e72-b794-b5e05e22ed61.png"> 

<img width="481" alt="Screenshot 2023-03-25 alle 22 13 11" src="https://user-images.githubusercontent.com/83889924/227742305-a90fd198-3167-4571-8ae6-f6d147499db5.png">

**Comment by Alex73hub** [comment]
<img width="339" alt="Screenshot 2023-03-25 alle 22 12 47" src="https://user-images.githubusercontent.com/83889924/227742341-f1b7a66a-46e5-48bf-8b16-766348498cde.png">

**Comment by Alex73hub** [comment]
last version

**Comment by Alex73hub** [comment]
Logger: homeassistant.config_entries
Source: helpers/network.py:206 
First occurred: 1 aprile 2023, 21:19:56 (1 occurrences) 
Last logged: 1 aprile 2023, 21:19:56

Error setting up entry Nuki for nuki_ng
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nuki_ng/__init__.py", line 26, in async_setup_entry
    coordinator = NukiCoordinator(hass, entry, data)
  File "/config/custom_components/nuki_ng/nuki.py", line 345, in __init__
    url = config.get("hass_url", get_url(hass))
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 167, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 206, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by liog22** [comment]
I have the same problem
