### ISSUE TITLE
Nuki battery level and status not updated

### ISSUE THREAD

**Issue by p2923260** [kvj/hass_nuki_ng#164]
The sensor battery does not refresh. I have charged the battery from 78% to 100% and it's correctly reported on Nuki App but the HA sensor does not change. In general I see a lot of repetitive warnings in the Nuki integration log.

File "/config/custom_components/nuki_ng/nuki.py", line 40, in async_json
    raise HomeAssistantError(f"Http response for {response.request.url}: {response.status_code} {response.reason}")
homeassistant.exceptions.HomeAssistantError: Http response for https://api.nuki.io/smartlock/(redacted)/auth: 401 Unauthorized
2023-11-04 08:30:04.447 WARNING (MainThread) [custom_components.nuki_ng.nuki] Despite being configured, Web API request has failed
2023-11-04 08:30:04.447 ERROR (MainThread) [custom_components.nuki_ng.nuki] Error while fetching auth:
Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/nuki.py", line 419, in _update
    item["web_auth"] = await self.api.web_list_all_auths(web_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/nuki.py", line 216, in web_list_all_auths
    response = await self.web_async_json(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/nuki.py", line 185, in web_async_json
    return await self.async_json(

**Comment by parkflyer** [comment]
Just installed my new Nuki 4.0 pro including this HA integration. Everything works fine except battery infos, the state is always at 0% and the charging indicator is constantly at false. 
Bonus question: How can I change the poll interval (default 30 sec) which I have set when installing the integration?

THX,
parkflyer

**Comment by parkflyer** [comment]
Update: With the firmware update of today battery state is working again, so it was an issue of Nuki, not the integration.
