### ISSUE TITLE
Error while setting up nuki_ng platform for sensor

### ISSUE THREAD

**Issue by Claudio1L** [kvj/hass_nuki_ng#181]
after update to 0.5.1 started receiving the following errors:
Was not present in 0.5.0

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:368
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 13:22:57 (1 occurrences)
Last logged: 13:22:57
Error while setting up nuki_ng platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 672, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/sensor.py", line 133, in icon
    state = self.get_state()
            ^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/sensor.py", line 147, in get_state
    door_sensor_state = DoorSensorStates(
                        ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 714, in __call__
    return cls._create_(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 853, in _create_
    _, first_enum = cls._get_mixins_(class_name, bases)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 952, in _get_mixins_
    mcls._check_for_existing_members_(class_name, bases)
  File "/usr/local/lib/python3.11/enum.py", line 936, in _check_for_existing_members_
    raise TypeError(
TypeError: <enum 2> cannot extend <enum 'DoorSensorStates'>

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 13:22:57 (1 occurrences)
Last logged: 13:22:57
Error adding entities for domain sensor with platform nuki_ng

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 672, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/sensor.py", line 133, in icon
    state = self.get_state()
            ^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/sensor.py", line 147, in get_state
    door_sensor_state = DoorSensorStates(
                        ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 714, in __call__
    return cls._create_(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 853, in _create_
    _, first_enum = cls._get_mixins_(class_name, bases)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 952, in _get_mixins_
    mcls._check_for_existing_members_(class_name, bases)
  File "/usr/local/lib/python3.11/enum.py", line 936, in _check_for_existing_members_
    raise TypeError(
TypeError: <enum 2> cannot extend <enum 'DoorSensorStates'>

![immagine](https://github.com/kvj/hass_nuki_ng/assets/97904190/98a42347-fd29-48f3-b10f-2e06982adc7a)

![immagine](https://github.com/kvj/hass_nuki_ng/assets/97904190/453e3e21-6a7f-4390-a633-ff671d8d3065)

**Comment by kvj** [comment]
Which HA version you're on?

**Comment by Claudio1L** [comment]
![immagine](https://github.com/kvj/hass_nuki_ng/assets/97904190/f1f5e17f-04f9-4ed8-8c02-7ef6250c69ed)

**Comment by leppa** [comment]
Same issue. If I revert [this change](https://github.com/kvj/hass_nuki_ng/compare/0.5.0...0.5.1#diff-a2506816dec6f29d5dade94bf48fcefc65074b4f166e4996d18239fcb0aaedf4L148) (line 148 in `sensor.py`), the sensor works again.

**Comment by Claudio1L** [comment]
Thanks. After reverting line 148 in sensor.py start working also for me.

**Comment by CAVACO-PT** [comment]
Same issue 

Version of the nuke app   -   2.15.3

Core
2024.1.3
Supervisor
2023.12.1
Operating System
11.4
Frontend
20240104.0

It stopped working after i updated to the lastest version of the nuki app

**Comment by kvj** [comment]
Hi @inc-ali could you please take a look? I guess your PR is causing issues on some environments

**Comment by isibizi** [comment]
> Same issue. If I revert [this change](https://github.com/kvj/hass_nuki_ng/compare/0.5.0...0.5.1#diff-a2506816dec6f29d5dade94bf48fcefc65074b4f166e4996d18239fcb0aaedf4L148) (line 148 in `sensor.py`), the sensor works again.

Worked for me to

**Comment by inc-ali** [comment]
> Hi @inc-ali could you please take a look? I guess your PR is causing issues on some environments

@kvj please merge :)

**Comment by kvj** [comment]
Updated to 0.5.2
