### ISSUE TITLE
"configuration failed"

### ISSUE THREAD

**Issue by Fougues** [kvj/hass_nuki_ng#184]
Hi,
I've been going in circles for several weeks
I can't get the "NUKI LOCK" integration to work

I have a Nuki smart lock PRO 4 connected by a Bridge

I have done and restarted dozens of times but I still get the same error.

It tells me "SUCCESSED" but it also tells me "configuration failed"

![nuki1](https://github.com/kvj/hass_nuki_ng/assets/107277496/307fe5cc-e80e-44e7-8c99-35dc9fc86095)
![Nuki2](https://github.com/kvj/hass_nuki_ng/assets/107277496/11555bac-d742-48ec-a556-ada556d77744)

**Comment by Fougues** [comment]
This is my log:

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 10:35:45 (4 occurrences)
Last logged: 14:11:11

Error setting up entry Maison for nuki_ng
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/__init__.py", line 26, in async_setup_entry
    coordinator = NukiCoordinator(hass, entry, data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/nuki.py", line 373, in __init__
    url = config.get("hass_url", get_url(hass))
                                 ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
