### ISSUE TITLE
Smartlock: 502 Bad Gateway

### ISSUE THREAD

**Issue by developerGM** [kvj/hass_nuki_ng#200]
From some days I have a problem with this nuki integration.
I have changed the router but I have connected to new Wifi the Nuki Bridge.
The nuki app works perfectly but in HA I have this log

`Error while fetching list of devices via web API:
Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/nuki.py", line 439, in _update
    web_list = await self.api.web_list()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/nuki.py", line 297, in web_list
    resp = await self.web_async_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/nuki.py", line 186, in web_async_json
    return await self.async_json(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nuki_ng/nuki.py", line 41, in async_json
    raise HomeAssistantError(f"Http response for {response.request.url}: {response.status_code} {response.reason}")
homeassistant.exceptions.HomeAssistantError: Http response for https://api.nuki.io/smartlock: 502 Bad Gateway`

**Comment by KHOne23** [comment]
Same Problem here, State of Lock is wrong. Its open and shows locked.

**Comment by developerGM** [comment]
Yes, every day I see in the log many times become unavailable...than available again.
I have locked the internal IP on the router so I am sure that this not change.
I don't know why

**Comment by kvj** [comment]
Based on the stack trace, it's not a device and/or integration issue, but a Nuki Web API endpoint availability. If Nuki Web API isn't stable these days, try to disable it (remove Web token from the configuration)

**Comment by developerGM** [comment]
Ok I can disable in these days and remove webtoken, but I need to insert again with new token? or I can't use the integration for some days?

**Comment by kvj** [comment]
The integration will work. Web API is only needed for the following:
![image](https://github.com/user-attachments/assets/5a7baee3-5c74-49d8-b7af-65f1b5ec36fd)

**Comment by developerGM** [comment]
Sorry, can you explain how do.
I open in ha the Nuki integration...and here I see 2 devices (Nuki and Nuki Web API)
click on Nuki Web API and disable all configuration switches?

**Comment by kvj** [comment]
No, you need to remove the integration and add it again, leaving the web token field empty

**Comment by developerGM** [comment]
I am trying to use Bridge token, but this is the error
"Error communicating with Nuki bridge"

**Comment by kvj** [comment]
Well, if you don't have a Nuki bridge (I'm not aware of your setup) and Web API is the only option for you - then you're out of luck. I don't know what's happening to the Nuki Web infrastructure

**Comment by developerGM** [comment]
Ok, I added integration using bridge token. 
Let's see if it still loses connection
thanks

**Comment by limakilo-root** [comment]
> Ok, I added integration using bridge token. Let's see if it still loses connection thanks

Post a feedback, if anything changes. I do run into the same issues. 
TY

**Comment by developerGM** [comment]
Confirm that with this modification it works.
