### ISSUE TITLE
Upgrade from Gen3 to Ultra

### ISSUE THREAD

**Issue by quadjojo** [kvj/hass_nuki_ng#201]
While installing my new smartlock, HA startet throwing errors. 
I removed the old smartlock from nukiweb, removed the api key and generated a new one, also reinstalled the nuki_ng integration.
When I now add the new webapi key / lock it is added in HA but doesn't work.

Is the Ultra supported or does nuki_ng need an update?

Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/nuki.py", line 447, in _update
    raise HomeAssistantError("No available device data")
homeassistant.exceptions.HomeAssistantError: No available device data

Thank you in advance!
Toby

**Comment by vinnygogo** [comment]
I have freshly installed this integration as i am a new Nuki Ultra user. Running into the same issue. Hope someone can assist!

Logger: custom_components.nuki_ng.nuki
Source: custom_components/nuki_ng/nuki.py:447
integration: Nuki Lock ([documentation](https://github.com/kvj/hass_nuki_ng), [issues](https://github.com/kvj/hass_nuki_ng/issues))
First occurred: 17:34:05 (15 occurrences)
Last logged: 17:41:29

Failed to get latest data: No available device data
Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/nuki.py", line 447, in _update
    raise HomeAssistantError("No available device data")
homeassistant.exceptions.HomeAssistantError: No available device data

**Comment by candyman2903** [comment]
Thanks for testing. I'll wait until it works before I buy it.

**Comment by quadjojo** [comment]
Im using Matter now instead of this Integration. Works perfect

**Comment by modem7** [comment]
> Im using Matter now instead of this Integration. Works perfect 

What sensors does it expose via matter?
