### ISSUE TITLE
Failed to update callback

### ISSUE THREAD

**Issue by kordys** [kvj/hass_nuki_ng#22]
Hi,

I've just configured the integration and it looks like everything works as expected, but when checking the log I found several error messages:

`2021-12-15 21:38:49 ERROR (MainThread) [custom_components.nuki_ng.nuki] Failed to update callback https://kordynet.duckdns.org:8123/api/webhook/nuki_ng_bridge_hook_xxx
Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/nuki.py", line 268, in _update
    callbacks_list = await self.api.bridge_check_callback(self.bridge_hook)
  File "/config/custom_components/nuki_ng/nuki.py", line 129, in bridge_check_callback
    result = await self.async_json(
  File "/config/custom_components/nuki_ng/nuki.py", line 40, in async_json
    raise ConnectionError(f"Http response: {response.status_code}")
ConnectionError: Http response: 400`

Do you have any clue what should I check or where can be the issue? It looks like the web hook is created automatically by the integration os I don't know where and what to check.

Thanks a lot.

**Comment by alexdelprete** [comment]
I noticed you're using duckdns. The bridge doesn't support HTTPS, so it can't call back on an HTTPS url. I wonder how it seems to be working. Only polling...

**Comment by kordys** [comment]
Thanks for the reply. So the only chance is to use http optionally with local IP address only?

**Comment by kvj** [comment]
@kordys yes, http url accessible by the bridge should be enough to resolve the issue

**Comment by dvdavide** [comment]
Strange thing happened when configuring the integration from the external address. The integration would install normally, except I didn't get a field for "Home Assistant internal URL" in the config page, then the callback would fail and I would get an error in the log: "Failed to update callback https://192.168.0.20:8123/api/webhook/nuki_ng_bridge_hook_xxxxxx"

(note the https)

removed integration, tried installing again from local address, found the Internal URL field, corrected to http, and the callback now works fine. Leaving a note here in case someone finds themselves in the same situation, until this is fixed.

**Comment by alexdelprete** [comment]
> when configuring the integration from the external address. The integration would install normally, except I didn't get a field for "Home Assistant internal URL" in the config page

No strange thing: there's no field for internal/external, just the URL, it's up to you to pick the correct URL. Since the bridge doesn't support SSL, you need to choose the appropriate http URL.
