### ISSUE TITLE
Eror communicating with Nuki Web API

### ISSUE THREAD

**Issue by agaleraib** [kvj/hass_nuki_ng#23]
Hello and thank you for this awesome development.

I am trying to install it but getting the error below. Can you please advice?

![image](https://user-images.githubusercontent.com/80838993/146371492-e571fdfd-53a0-4f3e-9733-fcde93273b72.png)

Here is the log:

2021-12-16 13:20:51 ERROR (MainThread) [custom_components.nuki_ng.config_flow] Failed to get list of devices from web API: Http response: 401
Traceback (most recent call last):
File "/config/custom_components/nuki_ng/config_flow.py", line 37, in find_nuki_devices
response = await nuki.web_list()
File "/config/custom_components/nuki_ng/nuki.py", line 173, in web_list
resp = await self.web_async_json(
File "/config/custom_components/nuki_ng/nuki.py", line 143, in web_async_json
return await self.async_json(lambda r: cb(r, {
File "/config/custom_components/nuki_ng/nuki.py", line 40, in async_json
raise ConnectionError(f"Http response: {response.status_code}")
ConnectionError: Http response: 401

**Comment by agaleraib** [comment]
It worked now! I think it was an issue with Nuki web.

**Comment by kvj** [comment]
Closing, as the issue has been resolved
