### ISSUE TITLE
Integration add fail

### ISSUE THREAD

**Issue by bigboban** [kvj/hass_nuki_ng#3]
When i try add "Nuki lock" integration i receive this:

Error
Config flow could not be loaded

**Comment by alexdelprete** [comment]
When you first install the component and then go to integrations to add it, make sure to do a "hard" refresh of the browser (ctrl-F5), sometimes there's this problem with config flow because of caching issues.

**Comment by kvj** [comment]
@bigboban a stack trace from the log file will also help

**Comment by hennesph** [comment]
`
Log Details (ERROR)
Logger: aiohttp.server
Source: helpers/network.py:116
First occurred: 3:37:38 PM (1 occurrences)
Last logged: 3:37:38 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 224, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/nuki_ng/config_flow.py", line 40, in async_step_user
    hass_url = get_url(self.hass)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 116, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
`

**Comment by alexdelprete** [comment]
> I have the same issue. I switched to https for my installation, after that the integration did not work as it did before. I reinstalled the integration (from configuration / integrations) and restarted HA between the deinstall / install. now I get the same error as above, also after reloading / cache delete or using a different browser.

Nuki Bridge does not support https. This means HA must be accessible through HTTP, otherwise the Bridge cannot communicate with the integration.

**Comment by kvj** [comment]
@alexdelprete is right, in general. but the stack trace above reports a different problem.

For some reason HASS itself is failing to detect its own URL, as this call isn't mandatory I will ignore this error.

@hennesph you can manually set HASS internal and external URLs in server settings (with advanced settings enabled) to resolve the issue
