### ISSUE TITLE
After HA Reboot - " (...) Failed to update callback (...) Http response: 503"

### ISSUE THREAD

**Issue by anthonws** [kvj/hass_nuki_ng#66]
Is this expected, after HA reboots?? Is it a question of Bridge capacity?

```
2022-06-22 10:22:08 ERROR (MainThread) [custom_components.nuki_ng.nuki] Failed to update callback http://192.168.25.9:8123/api/webhook/nuki_ng_bridge_hook_xxxxxxxxx
Traceback (most recent call last):
File "/config/custom_components/nuki_ng/nuki.py", line 339, in _update
callbacks_list = await self.api.bridge_check_callback(
File "/config/custom_components/nuki_ng/nuki.py", line 146, in bridge_check_callback
callbacks = await self.async_json(
File "/config/custom_components/nuki_ng/nuki.py", line 38, in async_json
raise ConnectionError(f"Http response: {response.status_code}")
ConnectionError: Http response: 503
2022-06-22 10:22:08 ERROR (MainThread) [custom_components.nuki_ng.nuki] Failed to get latest data: Http response: 503
Traceback (most recent call last):
File "/config/custom_components/nuki_ng/nuki.py", line 344, in _update
bridge_info = await self.api.bridge_info()
File "/config/custom_components/nuki_ng/nuki.py", line 72, in bridge_info
return await self.async_json(lambda r: r.get(self.bridge_url("/info")))
File "/config/custom_components/nuki_ng/nuki.py", line 38, in async_json
raise ConnectionError(f"Http response: {response.status_code}")
ConnectionError: Http response: 503
2022-06-22 10:22:08 ERROR (MainThread) [custom_components.nuki_ng.nuki] Error fetching nuki_ng data: 
```

**Comment by alexdelprete** [comment]
the bridge is very limited, it can only manage 1 request at a time, if two requests arrive at the same time, it throws error 503.

Make sure you are using only this component, not in parallel to the official one as that leads to these errors.

Also, if you have the mobile app open doing things, you have multiple requests to the bridge.

**Comment by anthonws** [comment]
Understood! Thanks for the input!
