### ISSUE TITLE
Lock not functioning since version 0.3.7

### ISSUE THREAD

**Issue by ShayGus** [kvj/hass_nuki_ng#86]
Since 0.3.7 the lock doesn't loads on startup.
Downgrading to 0.3.6 solves the issue.
Attaching the logs:

2022-08-26 11:37:51.432 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nuki_ng which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-26 11:38:00.516 ERROR (MainThread) [custom_components.nuki_ng.nuki] Failed to get latest data: Http response for https://api.nuki.io/smartlock: 401 Unauthorized
File "/config/custom_components/nuki_ng/nuki.py", line 386, in _update
File "/config/custom_components/nuki_ng/nuki.py", line 265, in web_list
File "/config/custom_components/nuki_ng/nuki.py", line 181, in web_async_json
File "/config/custom_components/nuki_ng/nuki.py", line 38, in async_json
2022-08-26 11:38:00.517 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Home Lock' for nuki_ng integration not ready yet; Retrying in background
2022-08-26 11:38:25.950 ERROR (MainThread) [custom_components.nuki_ng.nuki] Failed to get latest data: Http response for https://api.nuki.io/smartlock: 401 Unauthorized
File "/config/custom_components/nuki_ng/nuki.py", line 386, in _update
File "/config/custom_components/nuki_ng/nuki.py", line 265, in web_list
File "/config/custom_components/nuki_ng/nuki.py", line 181, in web_async_json
File "/config/custom_components/nuki_ng/nuki.py", line 38, in async_json
2022-08-26 11:38:36.645 ERROR (MainThread) [custom_components.nuki_ng.nuki] Failed to get latest data: Http response for https://api.nuki.io/smartlock: 401 Unauthorized
File "/config/custom_components/nuki_ng/nuki.py", line 386, in _update
File "/config/custom_components/nuki_ng/nuki.py", line 265, in web_list
File "/config/custom_components/nuki_ng/nuki.py", line 181, in web_async_json
File "/config/custom_components/nuki_ng/nuki.py", line 38, in async_json

**Comment by kvj** [comment]
Did you enter your Web API token when you configured the integration?

**Comment by ShayGus** [comment]
My integration works fine when on 0.3.6.
Also with the web API.
When I upgrade to 3.3.7 or 3.3.8 it fails to start.
When I downgrade back it works again.

**Comment by kvj** [comment]
What scopes did you enable for your web api token?

it is true that working API connection is now required when it's configured. I can suppress startup error, but in such case you won't get all the features you expect

**Comment by kvj** [comment]
You can give it a try using current `main` branch

**Comment by ShayGus** [comment]
3.9 is working. 
I have all scopes enabled and still I get this error.

This error originated from a custom integration.

Logger: custom_components.nuki_ng.nuki
Source: custom_components/nuki_ng/nuki.py:38
Integration: Nuki Lock (documentation, issues)
First occurred: 16:33:54 (372 occurrences)
Last logged: 17:37:30

Error while fetching list of devices via web API:
Error while fetching auth:
Error while fetching last log entry
Traceback (most recent call last):
  File "/config/custom_components/nuki_ng/nuki.py", line 387, in _update
    web_list = await self.api.web_list()
  File "/config/custom_components/nuki_ng/nuki.py", line 265, in web_list
    resp = await self.web_async_json(
  File "/config/custom_components/nuki_ng/nuki.py", line 181, in web_async_json
    return await self.async_json(
  File "/config/custom_components/nuki_ng/nuki.py", line 38, in async_json
    raise ConnectionError(f"Http response for {response.request.url}: {response.status_code} {response.reason}")
ConnectionError: Http response for https://api.nuki.io/smartlock: 401 Unauthorized

![SmartSelect_20220826-173611_Chrome](https://user-images.githubusercontent.com/2332415/186929792-72923507-f29b-4880-84a4-fb22aa33a859.jpg)
![SmartSelect_20220826-173611_Chrome](https://user-images.githubusercontent.com/2332415/186929850-e63d3a5d-0139-4b6b-a0b6-731fc587c154.jpg)

**Comment by kvj** [comment]
good, but I doubt that web API works in your case. 
I think you're in bridge-only mode
